using System.Globalization;
using System.Resources;

namespace PerformanceManagement.Core.Resources;

/// <summary>
/// Marker type + thin lookup helper for EmailResource.resx / EmailResource.ar.resx — plain
/// System.Resources.ResourceManager rather than Microsoft.Extensions.Localization, since Core
/// has no ASP.NET Core dependency and email is generated by static methods, not DI-injected
/// page/service instances. Defaults to CultureInfo.CurrentUICulture (set by the request's
/// culture middleware) but callers on the email path pass the recipient's own PreferredCulture
/// explicitly instead, since email is composed on behalf of someone who isn't making the request.
/// </summary>
public static class EmailResource
{
    private static readonly ResourceManager Manager = new(typeof(EmailResource));

    public static string Get(string key, CultureInfo? culture = null) =>
        Manager.GetString(key, culture ?? CultureInfo.CurrentUICulture) ?? key;

    /// <summary>Same lookup, then <see cref="string.Format(string, object?[])"/>'d with the given
    /// arguments — for the many labels/subjects/sentences that carry a name, date, or count.</summary>
    public static string Get(string key, CultureInfo? culture, params object?[] args) =>
        string.Format(Get(key, culture), args);
}
