// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PerformanceManagement.Core.Data;

#nullable disable

namespace PerformanceManagement.Core.Data.Migrations
{
    [DbContext(typeof(PmDbContext))]
    [Migration("20260714070507_AddSystemSettings")]
    partial class AddSystemSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PerformanceManagement.Core.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("EmpCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.CompetencyMaster", b =>
                {
                    b.Property<string>("CompId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CompType")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("DeptCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeptDesc")
                        .HasColumnType("text");

                    b.Property<string>("DeptDescAr")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("integer");

                    b.Property<int>("MinWeight")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedTime")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDesc")
                        .HasColumnType("text");

                    b.Property<string>("TypeDescAr")
                        .HasColumnType("text");

                    b.Property<string>("WeightRange")
                        .HasColumnType("text");

                    b.HasKey("CompId");

                    b.ToTable("CompetencyMasters");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.Department", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.Designation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CcRecipients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormLegacyRefNo")
                        .HasColumnType("text");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ToRecipients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey");

                    b.ToTable("EmailLogs");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.Employee", b =>
                {
                    b.Property<string>("EmpCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ArabicName")
                        .HasColumnType("text");

                    b.Property<string>("DeptCode")
                        .HasColumnType("text");

                    b.Property<string>("DesignationCode")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateOnly?>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SectionCode")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("TermDate")
                        .HasColumnType("date");

                    b.HasKey("EmpCode");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.EmployeeException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpCode", "RuleCode");

                    b.ToTable("EmployeeExceptions");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.ImpersonationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImpersonatedDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpersonatedEmpCode")
                        .HasColumnType("text");

                    b.Property<string>("ImpersonatedUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("StartedAt");

                    b.ToTable("ImpersonationLogs");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.JobFamily", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("CompWeight")
                        .HasColumnType("integer");

                    b.Property<string>("GradesCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KpiWeight")
                        .HasColumnType("integer");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("JobFamilies");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.KpiMaster", b =>
                {
                    b.Property<string>("KpiId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("DeptCsv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeptDesc")
                        .HasColumnType("text");

                    b.Property<string>("DeptDescAr")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.Property<string>("Formula")
                        .HasColumnType("text");

                    b.Property<string>("FormulaAr")
                        .HasColumnType("text");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("integer");

                    b.Property<int>("MinWeight")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("ModifiedDate")
                        .HasColumnType("date");

                    b.Property<string>("ModifiedTime")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("Perspective")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("PerspectiveDesc")
                        .HasColumnType("text");

                    b.Property<string>("PerspectiveDescAr")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeightRange")
                        .HasColumnType("text");

                    b.HasKey("KpiId");

                    b.ToTable("KpiMasters");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.ManagerAssignment", b =>
                {
                    b.Property<string>("EmpCode")
                        .HasColumnType("text");

                    b.Property<string>("ManagerEmpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmpCode");

                    b.ToTable("ManagerAssignments");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("CompWeightTotal")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DeptCode")
                        .HasColumnType("text");

                    b.Property<string>("DesignationSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("DevelopmentPlan")
                        .HasColumnType("text");

                    b.Property<string>("EmpAckBy")
                        .HasColumnType("text");

                    b.Property<string>("EmpAckComments")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("EmpAckDate")
                        .HasColumnType("date");

                    b.Property<string>("EmpAckSign")
                        .HasColumnType("text");

                    b.Property<string>("EmpCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmpNameSnapshot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeSign")
                        .HasColumnType("text");

                    b.Property<int>("EvalYear")
                        .HasColumnType("integer");

                    b.Property<string>("GradeSnapshot")
                        .HasColumnType("text");

                    b.Property<string>("Hr1Remarks")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Hr1ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("Hr1ReviewerName")
                        .HasColumnType("text");

                    b.Property<string>("Hr1Sign")
                        .HasColumnType("text");

                    b.Property<string>("Hr2Remarks")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Hr2ReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("Hr2ReviewerName")
                        .HasColumnType("text");

                    b.Property<string>("Hr2Sign")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("JobFamily")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("JoinDateSnapshot")
                        .HasColumnType("date");

                    b.Property<decimal>("KpiScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<int>("KpiWeightTotal")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastRemindedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastReviewDate")
                        .HasColumnType("date");

                    b.Property<string>("LegacyRefNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ManagerEmpCode")
                        .HasColumnType("text");

                    b.Property<string>("ManagerSign")
                        .HasColumnType("text");

                    b.Property<string>("OverallRatingCode")
                        .HasColumnType("text");

                    b.Property<decimal>("PerformanceScore")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PromotionComments")
                        .HasColumnType("text");

                    b.Property<string>("PromotionRecommendationValue")
                        .HasColumnType("text");

                    b.Property<string>("SectionCode")
                        .HasColumnType("text");

                    b.Property<string>("SelfAssessment")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("StatusChangeDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LegacyRefNo")
                        .IsUnique();

                    b.HasIndex("EmpCode", "EvalYear")
                        .IsUnique();

                    b.ToTable("PmForms");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmFormCompetency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementScore")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("CompCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ItemWeight")
                        .HasColumnType("integer");

                    b.Property<string>("LegacyRefNo")
                        .HasColumnType("text");

                    b.Property<int>("PmFormId")
                        .HasColumnType("integer");

                    b.Property<int>("RecordSeq")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightedCalculation")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("PmFormId", "RecordSeq")
                        .IsUnique();

                    b.ToTable("PmFormCompetencies");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmFormKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementScore")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<string>("FormulaMetric")
                        .HasColumnType("text");

                    b.Property<int>("ItemWeight")
                        .HasColumnType("integer");

                    b.Property<string>("KpiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KpiDefinition")
                        .HasColumnType("text");

                    b.Property<string>("KpiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LegacyRefNo")
                        .HasColumnType("text");

                    b.Property<string>("Perspective")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PmFormId")
                        .HasColumnType("integer");

                    b.Property<int>("RecordSeq")
                        .HasColumnType("integer");

                    b.Property<string>("Target")
                        .HasColumnType("text");

                    b.Property<decimal>("WeightedCalculation")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("PmFormId", "RecordSeq")
                        .IsUnique();

                    b.ToTable("PmFormKpis");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmFormStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PmFormId")
                        .HasColumnType("integer");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PmFormId");

                    b.ToTable("PmFormStatusHistory");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.RatingScale", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int>("MinScore")
                        .HasColumnType("integer");

                    b.Property<string>("NameAr")
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("RatingScales");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.Section", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("DevelopmentRedirectEmail")
                        .HasColumnType("text");

                    b.Property<bool>("EnableEmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnType("text");

                    b.Property<bool>("SmtpEnableSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text");

                    b.Property<string>("SmtpPasswordProtected")
                        .HasColumnType("text");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpUsername")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmFormCompetency", b =>
                {
                    b.HasOne("PerformanceManagement.Core.Domain.PmForm", "PmForm")
                        .WithMany("Competencies")
                        .HasForeignKey("PmFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PmForm");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmFormKpi", b =>
                {
                    b.HasOne("PerformanceManagement.Core.Domain.PmForm", "PmForm")
                        .WithMany("Kpis")
                        .HasForeignKey("PmFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PmForm");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmFormStatusHistory", b =>
                {
                    b.HasOne("PerformanceManagement.Core.Domain.PmForm", "PmForm")
                        .WithMany("History")
                        .HasForeignKey("PmFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PmForm");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.UserRole", b =>
                {
                    b.HasOne("PerformanceManagement.Core.Domain.AppUser", "AppUser")
                        .WithMany("RolesList")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.AppUser", b =>
                {
                    b.Navigation("RolesList");
                });

            modelBuilder.Entity("PerformanceManagement.Core.Domain.PmForm", b =>
                {
                    b.Navigation("Competencies");

                    b.Navigation("History");

                    b.Navigation("Kpis");
                });
#pragma warning restore 612, 618
        }
    }
}
